---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.api.onmetal.de
  resources:
  - prefixes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - loadbalancerroutings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - loadbalancers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - loadbalancers/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - loadbalancers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - natgateways
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - natgateways/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - natgateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - networkinterfaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - networkinterfaces/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - networkinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - networks
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - networks/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - virtualips
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - virtualips/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - virtualips/status
  verbs:
  - get
  - patch
  - update
