---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apinet.api.onmetal.de
  resources:
  - publicips
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apinet.api.onmetal.de
  resources:
  - publicips/finalizers
  verbs:
  - update
- apiGroups:
  - apinet.api.onmetal.de
  resources:
  - publicips/status
  verbs:
  - get
  - patch
  - update
