---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: apinetlet-role
rules:
- apiGroups:
  - apinet.api.onmetal.de
  resources:
  - networks
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
  - delete
- apiGroups:
  - apinet.api.onmetal.de
  resources:
  - publicips
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
  - delete
