apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default
  - ../apinet-rbac
  - role_binding.yaml

patchesStrategicMerge:
  - patch-controller.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: apinetlet-controller-manager
    path: add-api-net-namespace.yaml
